//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAnaly.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PBAnaly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10矩形 {
            get {
                object obj = ResourceManager.GetObject("10矩形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3D {
            get {
                object obj = ResourceManager.GetObject("3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 最后 的本地化字符串。
        /// </summary>
        internal static string ab_atLast {
            get {
                return ResourceManager.GetString("ab_atLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string ab_close {
            get {
                return ResourceManager.GetString("ab_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string ab_last {
            get {
                return ResourceManager.GetString("ab_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string ab_next {
            get {
                return ResourceManager.GetString("ab_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一幅 的本地化字符串。
        /// </summary>
        internal static string ab_one {
            get {
                return ResourceManager.GetString("ab_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开当前帧 的本地化字符串。
        /// </summary>
        internal static string ab_open_cur_tif {
            get {
                return ResourceManager.GetString("ab_open_cur_tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string ab_saveTif {
            get {
                return ResourceManager.GetString("ab_saveTif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Black_Green_0 {
            get {
                object obj = ResourceManager.GetObject("Black_Green_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Black_Green_1 {
            get {
                object obj = ResourceManager.GetObject("Black_Green_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Black_Red_1 {
            get {
                object obj = ResourceManager.GetObject("Black_Red_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string btn_back_form_re {
            get {
                return ResourceManager.GetString("btn_back_form_re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string btn_delete_role {
            get {
                return ResourceManager.GetString("btn_delete_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string btn_delete_user {
            get {
                return ResourceManager.GetString("btn_delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string btn_edit_password_role {
            get {
                return ResourceManager.GetString("btn_edit_password_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改权限 的本地化字符串。
        /// </summary>
        internal static string btn_editRole_head {
            get {
                return ResourceManager.GetString("btn_editRole_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改权限 的本地化字符串。
        /// </summary>
        internal static string btn_fix_role {
            get {
                return ResourceManager.GetString("btn_fix_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string btn_FixPassword {
            get {
                return ResourceManager.GetString("btn_FixPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回 的本地化字符串。
        /// </summary>
        internal static string btn_Frin_Password {
            get {
                return ResourceManager.GetString("btn_Frin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string btn_re_register {
            get {
                return ResourceManager.GetString("btn_re_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string btn_role_manage {
            get {
                return ResourceManager.GetString("btn_role_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string btn_role_save {
            get {
                return ResourceManager.GetString("btn_role_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string btn_SystemSetting {
            get {
                return ResourceManager.GetString("btn_SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string btn_UserManager {
            get {
                return ResourceManager.GetString("btn_UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是显示条带 的本地化字符串。
        /// </summary>
        internal static string cb_alwaysShowBands {
            get {
                return ResourceManager.GetString("cb_alwaysShowBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是显示泳道 的本地化字符串。
        /// </summary>
        internal static string cb_alwaysShowLane {
            get {
                return ResourceManager.GetString("cb_alwaysShowLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续绘制 的本地化字符串。
        /// </summary>
        internal static string cb_continuous {
            get {
                return ResourceManager.GetString("cb_continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统一泳道宽度 的本地化字符串。
        /// </summary>
        internal static string cb_lane_width {
            get {
                return ResourceManager.GetString("cb_lane_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住登录 的本地化字符串。
        /// </summary>
        internal static string cb_Remember {
            get {
                return ResourceManager.GetString("cb_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光子量 的本地化字符串。
        /// </summary>
        internal static string cb_scientific {
            get {
                return ResourceManager.GetString("cb_scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锐化 的本地化字符串。
        /// </summary>
        internal static string cb_sharpen {
            get {
                return ResourceManager.GetString("cb_sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整合 的本地化字符串。
        /// </summary>
        internal static string clasi_conformity {
            get {
                return ResourceManager.GetString("clasi_conformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始井 的本地化字符串。
        /// </summary>
        internal static string clasi_init {
            get {
                return ResourceManager.GetString("clasi_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泳道 的本地化字符串。
        /// </summary>
        internal static string clasi_lanes {
            get {
                return ResourceManager.GetString("clasi_lanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条带 的本地化字符串。
        /// </summary>
        internal static string clasi_strips {
            get {
                return ResourceManager.GetString("clasi_strips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像调整 的本地化字符串。
        /// </summary>
        internal static string collapseItem1 {
            get {
                return ResourceManager.GetString("collapseItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI工具 的本地化字符串。
        /// </summary>
        internal static string collapseItem2 {
            get {
                return ResourceManager.GetString("collapseItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工具 的本地化字符串。
        /// </summary>
        internal static string collapseItem3 {
            get {
                return ResourceManager.GetString("collapseItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string crownLabel1 {
            get {
                return ResourceManager.GetString("crownLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string fb_fixSetting {
            get {
                return ResourceManager.GetString("fb_fixSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        internal static string flb_brightness {
            get {
                return ResourceManager.GetString("flb_brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色阶 的本地化字符串。
        /// </summary>
        internal static string foxLabel2 {
            get {
                return ResourceManager.GetString("foxLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        internal static string foxLabel3 {
            get {
                return ResourceManager.GetString("foxLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码？点击找回 的本地化字符串。
        /// </summary>
        internal static string lab_forget_pass {
            get {
                return ResourceManager.GetString("lab_forget_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string label_DeleteTips {
            get {
                return ResourceManager.GetString("label_DeleteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string label_enterPassword {
            get {
                return ResourceManager.GetString("label_enterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string label_Language {
            get {
                return ResourceManager.GetString("label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string label_password_formUserManage {
            get {
                return ResourceManager.GetString("label_password_formUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string label_path {
            get {
                return ResourceManager.GetString("label_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 答案 的本地化字符串。
        /// </summary>
        internal static string label_re_Answer {
            get {
                return ResourceManager.GetString("label_re_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string label_re_password {
            get {
                return ResourceManager.GetString("label_re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密保问题 的本地化字符串。
        /// </summary>
        internal static string label_re_question {
            get {
                return ResourceManager.GetString("label_re_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string label_re_userNma {
            get {
                return ResourceManager.GetString("label_re_userNma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string label_role_userName {
            get {
                return ResourceManager.GetString("label_role_userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string label_Username_form_userManage {
            get {
                return ResourceManager.GetString("label_Username_form_userManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string label1_role {
            get {
                return ResourceManager.GetString("label1_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的密码 的本地化字符串。
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 的本地化字符串。
        /// </summary>
        internal static string label2_mode {
            get {
                return ResourceManager.GetString("label2_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密保问题 的本地化字符串。
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 答案 的本地化字符串。
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泳道宽度(像素) 的本地化字符串。
        /// </summary>
        internal static string lb_lane_width {
            get {
                return ResourceManager.GetString("lb_lane_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反式荧光 的本地化字符串。
        /// </summary>
        internal static string lb_top_info {
            get {
                return ResourceManager.GetString("lb_top_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泳道分析 的本地化字符串。
        /// </summary>
        internal static string materialButton_acidAnalyze {
            get {
                return ResourceManager.GetString("materialButton_acidAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据分析 的本地化字符串。
        /// </summary>
        internal static string materialButton_analyzedata {
            get {
                return ResourceManager.GetString("materialButton_analyzedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蛋白归一化 的本地化字符串。
        /// </summary>
        internal static string materialButton_correction {
            get {
                return ResourceManager.GetString("materialButton_correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泳道波形图 的本地化字符串。
        /// </summary>
        internal static string materialButton_curveimage {
            get {
                return ResourceManager.GetString("materialButton_curveimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像处理 的本地化字符串。
        /// </summary>
        internal static string materialButton_imageProcess {
            get {
                return ResourceManager.GetString("materialButton_imageProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载图像 的本地化字符串。
        /// </summary>
        internal static string materialButton_LoadData {
            get {
                return ResourceManager.GetString("materialButton_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日志 的本地化字符串。
        /// </summary>
        internal static string materialButton_log {
            get {
                return ResourceManager.GetString("materialButton_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微孔版分析 的本地化字符串。
        /// </summary>
        internal static string materialButton_miniAnalyze {
            get {
                return ResourceManager.GetString("materialButton_miniAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出图像 的本地化字符串。
        /// </summary>
        internal static string materialButton_outimage {
            get {
                return ResourceManager.GetString("materialButton_outimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI分析 的本地化字符串。
        /// </summary>
        internal static string materialButton_roiAnalyze {
            get {
                return ResourceManager.GetString("materialButton_roiAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统操作 的本地化字符串。
        /// </summary>
        internal static string materialButton_setting {
            get {
                return ResourceManager.GetString("materialButton_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统一泳道宽度 的本地化字符串。
        /// </summary>
        internal static string materialCheckbox1 {
            get {
                return ResourceManager.GetString("materialCheckbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光/暗 主题 的本地化字符串。
        /// </summary>
        internal static string materialSwitch_UI {
            get {
                return ResourceManager.GetString("materialSwitch_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加条带 的本地化字符串。
        /// </summary>
        internal static string mb_addBands {
            get {
                return ResourceManager.GetString("mb_addBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加泳道 的本地化字符串。
        /// </summary>
        internal static string mb_addLanes {
            get {
                return ResourceManager.GetString("mb_addLanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菌落计数 的本地化字符串。
        /// </summary>
        internal static string mb_colonyCount {
            get {
                return ResourceManager.GetString("mb_colonyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除条带 的本地化字符串。
        /// </summary>
        internal static string mb_deleteBands {
            get {
                return ResourceManager.GetString("mb_deleteBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除泳道 的本地化字符串。
        /// </summary>
        internal static string mb_deleteLane {
            get {
                return ResourceManager.GetString("mb_deleteLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找条带 的本地化字符串。
        /// </summary>
        internal static string mb_findBands {
            get {
                return ResourceManager.GetString("mb_findBands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找泳道 的本地化字符串。
        /// </summary>
        internal static string mb_findLanes {
            get {
                return ResourceManager.GetString("mb_findLanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改初始井 的本地化字符串。
        /// </summary>
        internal static string mb_updateInitWell {
            get {
                return ResourceManager.GetString("mb_updateInitWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap roi_select {
            get {
                object obj = ResourceManager.GetObject("roi-select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string SettingForm {
            get {
                return ResourceManager.GetString("SettingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string SIGNIN_materialButton {
            get {
                return ResourceManager.GetString("SIGNIN_materialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap YellowHot_0 {
            get {
                object obj = ResourceManager.GetObject("YellowHot_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap YellowHot_1 {
            get {
                object obj = ResourceManager.GetObject("YellowHot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom-in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom-out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 主页面_图像编辑_正反片 {
            get {
                object obj = ResourceManager.GetObject("主页面-图像编辑-正反片", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 京仪科技定稿_画板_1_副本2 {
            get {
                object obj = ResourceManager.GetObject("京仪科技定稿_画板 1 副本2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 保存 {
            get {
                object obj = ResourceManager.GetObject("保存", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 保存1 {
            get {
                object obj = ResourceManager.GetObject("保存1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 保存图片 {
            get {
                object obj = ResourceManager.GetObject("保存图片", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 全屏 {
            get {
                object obj = ResourceManager.GetObject("全屏", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 关闭White {
            get {
                object obj = ResourceManager.GetObject("关闭White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 分析 {
            get {
                object obj = ResourceManager.GetObject("分析", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 前台 {
            get {
                object obj = ResourceManager.GetObject("前台", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 图片管理 {
            get {
                object obj = ResourceManager.GetObject("图片管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 圆形 {
            get {
                object obj = ResourceManager.GetObject("圆形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 圆形1 {
            get {
                object obj = ResourceManager.GetObject("圆形1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 圖片_20240731174523 {
            get {
                object obj = ResourceManager.GetObject("圖片_20240731174523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 執行日誌紀錄 {
            get {
                object obj = ResourceManager.GetObject("執行日誌紀錄", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 壁纸 {
            get {
                object obj = ResourceManager.GetObject("壁纸", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 導出 {
            get {
                object obj = ResourceManager.GetObject("導出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 控制窗口 {
            get {
                object obj = ResourceManager.GetObject("控制窗口", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 放大 {
            get {
                object obj = ResourceManager.GetObject("放大", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 数据报告 {
            get {
                object obj = ResourceManager.GetObject("数据报告", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 数据报告__1_ {
            get {
                object obj = ResourceManager.GetObject("数据报告 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 文本 {
            get {
                object obj = ResourceManager.GetObject("文本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 最大化white {
            get {
                object obj = ResourceManager.GetObject("最大化white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 最小化white {
            get {
                object obj = ResourceManager.GetObject("最小化white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 波形图 {
            get {
                object obj = ResourceManager.GetObject("波形图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 波形设置_未选中 {
            get {
                object obj = ResourceManager.GetObject("波形设置-未选中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 添加用户 {
            get {
                object obj = ResourceManager.GetObject("添加用户", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 登录_亮 {
            get {
                object obj = ResourceManager.GetObject("登录-亮", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 窗口最大化_操作_jurassic {
            get {
                object obj = ResourceManager.GetObject("窗口最大化_操作_jurassic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 线段 {
            get {
                object obj = ResourceManager.GetObject("线段", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 线段__1_ {
            get {
                object obj = ResourceManager.GetObject("线段 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 缩小 {
            get {
                object obj = ResourceManager.GetObject("缩小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 胶原蛋白 {
            get {
                object obj = ResourceManager.GetObject("胶原蛋白", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 蛋白质_01 {
            get {
                object obj = ResourceManager.GetObject("蛋白质-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 计数器 {
            get {
                object obj = ResourceManager.GetObject("计数器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 返回前台 {
            get {
                object obj = ResourceManager.GetObject("返回前台", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 重组蛋白_CAR_T靶点蛋白 {
            get {
                object obj = ResourceManager.GetObject("重组蛋白-CAR-T靶点蛋白", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 重置 {
            get {
                object obj = ResourceManager.GetObject("重置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 风控 {
            get {
                object obj = ResourceManager.GetObject("风控", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 饼干 {
            get {
                object obj = ResourceManager.GetObject("饼干", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 魔术棒_魔法_魔术_一键 {
            get {
                object obj = ResourceManager.GetObject("魔术棒,魔法,魔术,一键", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 黑白平衡 {
            get {
                object obj = ResourceManager.GetObject("黑白平衡", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
